// Added isCompanyBrand flag, maxSize for other brands, and MOQ
import type { Product } from "./types"

export const PRODUCTS: Product[] = [
  // ============================================
  // COMPANY'S BRAND PRODUCTS - LOTUS SERIES
  // ============================================
  // Fixed sizes for Lotus brand products
  {
    id: "1",
    name: "LOTUS GALAXY RAW RICE",
    category: "Company's Brand",
    subcategory: "30 KG",
    price: 1200,
    description: "Premium galaxy raw rice - 30 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 50,
    rating: 4.8,
    reviews: 124,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "2",
    name: "LOTUS GALAXY PARBOILED RICE",
    category: "Company's Brand",
    subcategory: "30 KG",
    price: 1100,
    description: "Premium galaxy parboiled rice - 30 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 45,
    rating: 4.7,
    reviews: 98,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "3",
    name: "LOTUS CLASSIC BASMATI RICE",
    category: "Company's Brand",
    subcategory: "1 KG",
    price: 85,
    description: "Classic basmati rice - 1 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 200,
    rating: 4.9,
    reviews: 156,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "4",
    name: "LOTUS CLASSIC BASMATI RICE",
    category: "Company's Brand",
    subcategory: "5 KG",
    price: 380,
    description: "Classic basmati rice - 5 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 120,
    rating: 4.9,
    reviews: 145,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "5",
    name: "LOTUS CLASSIC BASMATI RICE",
    category: "Company's Brand",
    subcategory: "30 KG",
    price: 2100,
    description: "Classic basmati rice - 30 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 60,
    rating: 4.8,
    reviews: 189,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "6",
    name: "LOTUS ROYAL BASMATI RICE",
    category: "Company's Brand",
    subcategory: "1 KG",
    price: 95,
    description: "Royal basmati rice - 1 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 180,
    rating: 5.0,
    reviews: 201,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "7",
    name: "LOTUS ROYAL BASMATI RICE",
    category: "Company's Brand",
    subcategory: "5 KG",
    price: 420,
    description: "Royal basmati rice - 5 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 100,
    rating: 5.0,
    reviews: 178,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "8",
    name: "LOTUS ROYAL BASMATI RICE",
    category: "Company's Brand",
    subcategory: "30 KG",
    price: 2300,
    description: "Royal basmati rice - 30 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 75,
    rating: 5.0,
    reviews: 234,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "9",
    name: "LOTUS GOLDEN BASMATI RICE",
    category: "Company's Brand",
    subcategory: "1 KG",
    price: 105,
    description: "Golden basmati rice - 1 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 160,
    rating: 4.9,
    reviews: 167,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "10",
    name: "LOTUS GOLDEN BASMATI RICE",
    category: "Company's Brand",
    subcategory: "5 KG",
    price: 450,
    description: "Golden basmati rice - 5 KG pack",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 140,
    rating: 4.9,
    reviews: 198,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "11",
    name: "LOTUS SONA KATARNI RAW RICE",
    category: "Company's Brand",
    subcategory: "25 KG",
    price: 1050,
    description: "Sona katarni raw rice - 25 KG pack",
    image: "/white-rice-polished-pure.jpg",
    stock: 90,
    rating: 4.6,
    reviews: 112,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },
  {
    id: "12",
    name: "LOTUS SONA KATARNI STEAM RICE",
    category: "Company's Brand",
    subcategory: "25 KG",
    price: 1150,
    description: "Sona katarni steam rice - 25 KG pack",
    image: "/white-rice-polished-pure.jpg",
    stock: 85,
    rating: 4.7,
    reviews: 128,
    isCompanyBrand: true,
    minOrderQuantity: 25,
  },

  // ============================================
  // OTHER BRANDS - VARIABLE SIZES (MAX 50 KG)
  // ============================================
  // Rice Products
  {
    id: "13",
    name: "Basmati Rice - 1121",
    category: "Other Brands",
    subcategory: "Rice - Basmati",
    price: 420,
    description: "Premium white basmati rice variant 1121 - Variable size up to 50 KG",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 200,
    rating: 4.8,
    reviews: 145,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "14",
    name: "Basmati Rice - 1509",
    category: "Other Brands",
    subcategory: "Rice - Basmati",
    price: 450,
    description: "Premium golden basmati rice variant 1509 - Variable size up to 50 KG",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 180,
    rating: 4.8,
    reviews: 132,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "15",
    name: "Basmati Rice - 1718",
    category: "Other Brands",
    subcategory: "Rice - Basmati",
    price: 480,
    description: "Premium steam basmati rice variant 1718 - Variable size up to 50 KG",
    image: "/basmati-rice-premium-white-grains.jpg",
    stock: 160,
    rating: 4.9,
    reviews: 156,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "16",
    name: "IR 64 5% Broken Silky Sortex Raw Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 280,
    description: "IR 64 5% broken silky sortex raw rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 250,
    rating: 4.5,
    reviews: 98,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "17",
    name: "IR 64 25% Broken Sortex Raw Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 260,
    description: "IR 64 25% broken sortex raw rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 220,
    rating: 4.4,
    reviews: 85,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "18",
    name: "IR64 25% Broken Non Sortex Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 240,
    description: "IR 64 25% broken non sortex rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 200,
    rating: 4.3,
    reviews: 72,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "19",
    name: "IR64 5% Broken Parboiled Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 300,
    description: "IR 64 5% broken parboiled rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 180,
    rating: 4.6,
    reviews: 104,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "20",
    name: "100% Broken Sortex Raw Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 180,
    description: "100% broken sortex raw rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 300,
    rating: 4.2,
    reviews: 56,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "21",
    name: "Sona Masoori Raw Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 350,
    description: "Premium sona masoori raw rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 150,
    rating: 4.7,
    reviews: 118,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "22",
    name: "Sona Masoori Steam Rice",
    category: "Other Brands",
    subcategory: "Rice - Non Basmati",
    price: 380,
    description: "Premium sona masoori steam rice - Variable size up to 50 KG",
    image: "/white-rice-polished-pure.jpg",
    stock: 140,
    rating: 4.7,
    reviews: 125,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },

  // Maize Products
  {
    id: "23",
    name: "Maize - Grade A",
    category: "Other Brands",
    subcategory: "Grains - Maize",
    price: 320,
    description: "Premium maize grade A - Variable size up to 50 KG",
    image: "/mixed-grains-wheat-barley-oats.jpg",
    stock: 300,
    rating: 4.4,
    reviews: 67,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "24",
    name: "Maize - Grade B",
    category: "Other Brands",
    subcategory: "Grains - Maize",
    price: 300,
    description: "Premium maize grade B - Variable size up to 50 KG",
    image: "/mixed-grains-wheat-barley-oats.jpg",
    stock: 280,
    rating: 4.3,
    reviews: 55,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "25",
    name: "Maize - Grade C",
    category: "Other Brands",
    subcategory: "Grains - Maize",
    price: 280,
    description: "Premium maize grade C - Variable size up to 50 KG",
    image: "/mixed-grains-wheat-barley-oats.jpg",
    stock: 320,
    rating: 4.2,
    reviews: 48,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },

  // Pulses Products
  {
    id: "26",
    name: "Toor (Arahar) Dal",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 420,
    description: "Premium toor dal split variety - Variable size up to 50 KG",
    image: "/toor-dal-pulses.jpg",
    stock: 150,
    rating: 4.6,
    reviews: 89,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "27",
    name: "Urad Dal",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 450,
    description: "Premium urad dal split variety - Variable size up to 50 KG",
    image: "/urad-dal-pulses.jpg",
    stock: 120,
    rating: 4.5,
    reviews: 76,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "28",
    name: "Chana Dal",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 380,
    description: "Premium chana dal - Variable size up to 50 KG",
    image: "/chana-dal-pulses.jpg",
    stock: 180,
    rating: 4.7,
    reviews: 94,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "29",
    name: "Moong Dal",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 400,
    description: "Premium moong dal - Variable size up to 50 KG",
    image: "/moong-dal-pulses.jpg",
    stock: 160,
    rating: 4.6,
    reviews: 82,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "30",
    name: "Red Masoor Dal",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 360,
    description: "Premium red masoor dal - Variable size up to 50 KG",
    image: "/masoor-dal-red-pulses.jpg",
    stock: 200,
    rating: 4.7,
    reviews: 108,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },

  // Seeds Products
  {
    id: "31",
    name: "Mustard Seeds - Black",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 280,
    description: "Premium black mustard seeds - Variable size up to 50 KG",
    image: "/mustard-seeds.jpg",
    stock: 220,
    rating: 4.3,
    reviews: 61,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "32",
    name: "Mustard Seeds - Yellow",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 270,
    description: "Premium yellow mustard seeds - Variable size up to 50 KG",
    image: "/mustard-seeds.jpg",
    stock: 200,
    rating: 4.2,
    reviews: 52,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "33",
    name: "Sorghum Seeds",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 200,
    description: "Premium sorghum seeds - Variable size up to 50 KG",
    image: "/sorghum-grains-gluten-free.jpg",
    stock: 180,
    rating: 4.4,
    reviews: 55,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "34",
    name: "Pearl Millet",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 220,
    description: "Premium pearl millet seeds - Variable size up to 50 KG",
    image: "/pearl-millet-seeds.jpg",
    stock: 160,
    rating: 4.5,
    reviews: 63,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "35",
    name: "Soybean Seeds",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 350,
    description: "Premium soybean seeds - Variable size up to 50 KG",
    image: "/soybean-seeds.jpg",
    stock: 140,
    rating: 4.6,
    reviews: 71,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "36",
    name: "Foxtails (Makhana)",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 650,
    description: "Premium foxtails makhana - Variable size up to 50 KG",
    image: "/makhana-foxtails.jpg",
    stock: 80,
    rating: 4.8,
    reviews: 92,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "37",
    name: "Peanuts",
    category: "Other Brands",
    subcategory: "Seeds",
    price: 380,
    description: "Premium quality peanuts - Variable size up to 50 KG",
    image: "/peanuts-legumes.jpg",
    stock: 200,
    rating: 4.5,
    reviews: 79,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },

  // Grains & Other Products
  {
    id: "38",
    name: "Wheat (B Grade Milling)",
    category: "Other Brands",
    subcategory: "Grains - Wheat",
    price: 280,
    description: "B grade wheat for milling - Variable size up to 50 KG",
    image: "/wheat-milling-grains.jpg",
    stock: 250,
    rating: 4.3,
    reviews: 58,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "39",
    name: "Kidney Beans",
    category: "Other Brands",
    subcategory: "Pulses",
    price: 420,
    description: "Premium kidney beans - Variable size up to 50 KG",
    image: "/kidney-beans-legumes.jpg",
    stock: 130,
    rating: 4.6,
    reviews: 68,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },

  // Cattle Feed Products
  {
    id: "40",
    name: "Mustard Cake",
    category: "Other Brands",
    subcategory: "Cattle Feed",
    price: 150,
    description: "Premium mustard cake for cattle - Variable size up to 50 KG",
    image: "/mustard-cake-cattle-feed.jpg",
    stock: 400,
    rating: 4.2,
    reviews: 42,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "41",
    name: "Rice Husk",
    category: "Other Brands",
    subcategory: "Cattle Feed",
    price: 80,
    description: "Rice husk for cattle feed - Variable size up to 50 KG",
    image: "/rice-husk-cattle.jpg",
    stock: 500,
    rating: 4.1,
    reviews: 35,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "42",
    name: "Rice Bran",
    category: "Other Brands",
    subcategory: "Cattle Feed",
    price: 120,
    description: "Rice bran for cattle feed - Variable size up to 50 KG",
    image: "/rice-bran-cattle.jpg",
    stock: 450,
    rating: 4.3,
    reviews: 48,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
  {
    id: "43",
    name: "Wheat Bran",
    category: "Other Brands",
    subcategory: "Cattle Feed",
    price: 110,
    description: "Wheat bran for cattle feed - Variable size up to 50 KG",
    image: "/wheat-bran-cattle-feed.jpg",
    stock: 380,
    rating: 4.2,
    reviews: 44,
    isCompanyBrand: false,
    maxSize: 50,
    minOrderQuantity: 25,
  },
]
